-- CreateTable
CREATE TABLE "cvUser" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "name" STRING,

    CONSTRAINT "cvUser_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "cvUser_email_key" ON "cvUser"("email");
